---
- name: Установка и настройка Kibana с использованием зеркала Яндекс для пакетов
  hosts: kibana
  become: yes
  vars:
    elasticsearch_host: "{{ groups.elastic[0] }}"
    kibana_version: "8.19.7"
    
  tasks:
    # ========== 1. НАСТРОЙКА СИСТЕМЫ И РЕПОЗИТОРИЕВ ==========
    - name: Обновление системы через Яндекс зеркала
      apt:
        update_cache: yes
        cache_valid_time: 3600
      environment:
        http_proxy: "http://mirror.yandex.ru"
        https_proxy: "http://mirror.yandex.ru"

    - name: Установка необходимых утилит
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    # ========== 2. УСТАНОВКА ELASTICSEARCH РЕПОЗИТОРИЯ ==========
    - name: Скачивание GPG ключа Elasticsearch с официального источника
      get_url:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        dest: /tmp/GPG-KEY-elasticsearch
        timeout: 30
        headers:
          User-Agent: "curl/7.68.0"
      register: download_gpg

    - name: Импорт GPG ключа Elasticsearch
      apt_key:
        file: /tmp/GPG-KEY-elasticsearch
        state: present

    - name: Добавление репозитория Elasticsearch
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x
        update_cache: yes

    # ========== 3. НАСТРОЙКА APT ДЛЯ ИСПОЛЬЗОВАНИЯ ЯНДЕКС КАК МИРРОРА ==========
    - name: Создание конфигурации APT для использования Яндекс как зеркала
      copy:
        content: |
          Acquire::http::Proxy "http://mirror.yandex.ru:80";
          Acquire::https::Proxy "http://mirror.yandex.ru:80";
          
          # Приоритет Яндекс зеркал
          Acquire::http::Pipeline-Depth "0";
          Acquire::http::No-Cache "true";
          Acquire::BrokenProxy    "true";
        dest: /etc/apt/apt.conf.d/99yandex-mirror
        owner: root
        group: root
        mode: '0644'

    # ========== 4. УСТАНОВКА KIBANA ==========
    - name: Установка Kibana (будет использовать Яндекс как прокси)
      apt:
        name: "kibana={{ kibana_version }}"
        state: present
        update_cache: yes
        force: yes
      environment:
        http_proxy: "http://mirror.yandex.ru:80"
        https_proxy: "http://mirror.yandex.ru:80"
      register: kibana_install
      retries: 3
      delay: 10

    # ========== 5. ПРОВЕРКА УСТАНОВКИ ==========
    - name: Проверка установленной версии Kibana
      command: /usr/share/kibana/bin/kibana --version
      register: kibana_version_check
      changed_when: false
      ignore_errors: yes

    - name: Отображение версии Kibana
      debug:
        msg: "Установлена версия Kibana: {{ kibana_version_check.stdout }}"

    # ========== 6. СОЗДАНИЕ ДИРЕКТОРИЙ ==========
    - name: Создание необходимых директорий для Kibana
      file:
        path: "{{ item }}"
        state: directory
        owner: kibana
        group: kibana
        mode: '0755'
      loop:
        - /etc/kibana
        - /var/lib/kibana
        - /var/log/kibana
        - /var/run/kibana

    # ========== 7. КОНФИГУРАЦИЯ KIBANA ==========
    - name: Создание минимальной рабочей конфигурации kibana.yml
      copy:
        content: |
          # Основные настройки
          server.host: "0.0.0.0"
          server.port: 5601
          server.name: "kibana-server"
          
          # Elasticsearch
          elasticsearch.hosts: ["http://{{ elasticsearch_host }}:9200"]
          elasticsearch.requestTimeout: 90000
          elasticsearch.pingTimeout: 30000
          
          # Важная настройка для Kibana 8.x - обязательно!
          xpack.security.enabled: false
          
          # Ключи шифрования (требуются)
          xpack.encryptedSavedObjects.encryptionKey: "{{ 'min32charkeyforencryptionhere!' }}"
          xpack.reporting.encryptionKey: "{{ 'another32charkeyforreportinghere' }}"
          xpack.security.encryptionKey: "{{ 'security32charencryptionkeyhere!!' }}"
          
          # Отключаем ненужные функции
          xpack.fleet.enabled: false
          xpack.apm.enabled: false
          xpack.ml.enabled: false
          
          # Телеметрия
          telemetry.enabled: false
          telemetry.allowChangingOptInStatus: false
          
          # Оптимизация
          elasticsearch.healthCheck.delay: 60000
          elasticsearch.skipStartupConnectionCheck: true
          
          # Логирование
          logging.dest: /var/log/kibana/kibana.log
          logging.quiet: false
          logging.verbose: false
          
          # Русский язык
          i18n.locale: "ru"
        dest: /etc/kibana/kibana.yml
        owner: kibana
        group: kibana
        mode: '0640'
      notify:
        - Перезапуск Kibana

    # ========== 8. SYSTEMD СЛУЖБА ==========
    - name: Создание systemd службы
      copy:
        content: |
          [Unit]
          Description=Kibana
          Documentation=https://www.elastic.co
          Wants=network-online.target
          After=network-online.target
          
          [Service]
          Type=simple
          User=kibana
          Group=kibana
          Environment="KBN_PATH_CONF=/etc/kibana"
          Environment="NODE_OPTIONS=--max-old-space-size=512"
          ExecStart=/usr/share/kibana/bin/kibana
          Restart=always
          RestartSec=10
          LimitNOFILE=65536
          
          # Безопасность
          PrivateTmp=true
          NoNewPrivileges=true
          ProtectSystem=strict
          ReadWritePaths=/var/lib/kibana /var/log/kibana /var/run/kibana
          
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/kibana.service
        owner: root
        group: root
        mode: '0644'

    # ========== 9. НАСТРОЙКА ПРАВ ==========
    - name: Настройка прав для Kibana
      shell: |
        chown -R kibana:kibana /etc/kibana
        chown -R kibana:kibana /var/lib/kibana
        chown -R kibana:kibana /var/log/kibana
        chown -R kibana:kibana /var/run/kibana
        chmod 750 /var/lib/kibana
        chmod 750 /var/log/kibana
      changed_when: false

    # ========== 10. ЗАПУСК СЛУЖБЫ ==========
    - name: Перезагрузка systemd
      systemd:
        daemon_reload: yes

    - name: Включение автозапуска Kibana
      systemd:
        name: kibana
        enabled: yes

    - name: Запуск службы Kibana
      systemd:
        name: kibana
        state: started

    # ========== 11. ОЖИДАНИЕ ЗАПУСКА ==========
    - name: Ожидание запуска Kibana (60 секунд)
      pause:
        seconds: 60
        prompt: "Kibana запускается... Подождите 60 секунд"

    # ========== 12. ПРОВЕРКА СОСТОЯНИЯ ==========
    - name: Проверка состояния Kibana
      shell: |
        echo "=== ПРОВЕРКА KIBANA ==="
        echo ""
        echo "1. СТАТУС СЛУЖБЫ:"
        systemctl is-active kibana && echo "✓ Активна" || echo "✗ Неактивна"
        echo ""
        echo "2. ПРОЦЕССЫ:"
        ps aux | grep kibana | grep -v grep | wc -l | xargs echo "Количество:"
        echo ""
        echo "3. ПОРТ:"
        timeout 2 bash -c "echo > /dev/tcp/localhost/5601" 2>/dev/null && echo "✓ Порт 5601 открыт" || echo "✗ Порт 5601 закрыт"
        echo ""
        echo "4. ЛОГИ (последние 5 строк):"
        journalctl -u kibana -n 5 --no-pager 2>/dev/null || echo "Логи недоступны"
        echo ""
        echo "5. ОШИБКИ:"
        journalctl -u kibana --since "1 minute ago" --no-pager 2>/dev/null | grep -i "error\|fatal\|failed" || echo "Ошибок нет"
      register: status_check
      changed_when: false

    - name: Отображение статуса
      debug:
        msg: "{{ status_check.stdout_lines }}"

    # ========== 13. ПРОВЕРКА API ==========
    - name: Проверка доступности API Kibana
      uri:
        url: "http://localhost:5601/api/status"
        method: GET
        timeout: 30
        status_code: 200
        validate_certs: no
      register: api_test
      ignore_errors: yes
      retries: 10
      delay: 6
      until: api_test.status == 200

    # ========== 14. УДАЛЕНИЕ ПРОКСИ НАСТРОЙКИ APT ==========
    - name: Удаление прокси настроек APT (после установки)
      file:
        path: /etc/apt/apt.conf.d/99yandex-mirror
        state: absent
      ignore_errors: yes

    # ========== 15. ФИНАЛЬНЫЙ ОТЧЕТ ==========
    - block:
        - name: Успешная установка
          debug:
            msg: |
              🎉 KIBANA УСПЕШНО УСТАНОВЛЕН!
              
              🌐 Доступ по адресу:
              http://{{ ansible_default_ipv4.address }}:5601
              
              🔗 Elasticsearch:
              {{ elasticsearch_host }}:9200
              
              📊 Для проверки:
              curl http://localhost:5601/api/status
              
              ⚙️  Конфигурация:
              /etc/kibana/kibana.yml
              
              📦 Установка через: Elastic репозиторий с прокси через Яндекс
      when: api_test.status == 200

    - block:
        - name: Диагностика проблем
          debug:
            msg: |
              ⚠️  ПРОБЛЕМЫ С ЗАПУСКОМ KIBANA
              
              Действия для диагностики:
              
              1. Проверьте логи:
                 sudo journalctl -u kibana -f
              
              2. Проверьте конфигурацию:
                 sudo cat /etc/kibana/kibana.yml
              
              3. Проверьте процесс:
                 ps aux | grep kibana
              
              4. Проверьте порт:
                 netstat -tlnp | grep 5601
              
              5. Проверьте Elasticsearch:
                 curl {{ elasticsearch_host }}:9200
              
              ⏱️  Подождите еще 2-3 минуты и попробуйте снова
              
              📍 Адрес: http://{{ ansible_default_ipv4.address }}:5601
      when: api_test.status != 200

    # ========== 16. ОЧИСТКА ==========
    - name: Очистка временных файлов
      file:
        path: /tmp/GPG-KEY-elasticsearch
        state: absent

    - name: Очистка кэша APT
      apt:
        autoclean: yes
        autoremove: yes

  handlers:
    - name: Перезагрузка systemd
      systemd:
        daemon_reload: yes

    - name: Перезапуск Kibana
      systemd:
        name: kibana
        state: restarted
